os: Visual Studio 2015

version: 2.3.0-{branch}-{build}
environment:
    COVERALLS_REPO_TOKEN:
       secure: 8JYxwCWszeAaWBr41pD17LB925K7Sk7utvKsIb1qz44i2anf9uLmvh2q0ilMQTBO

cache:
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
  - ps: iex .\scripts\dotnet-latest.ps1
  # Prepend newly installed dotnet cli to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"
  - nuget sources add -Name https://api.nuget.org/v3/index.json -Source https://api.nuget.org/v3/index.json
  - nuget sources disable -Name nuget.org -Source https://www.nuget.org/api/v2
  - nuget sources list   # log what feeds we're using - in case of timeout

before_build:
  - ps: .\scripts\version-bump.ps1
  - appveyor-retry dotnet restore

test_script:
  - cmd: dotnet test .\test\Halcyon.Tests\

build_script:
  - ps: Get-ChildItem .\src\Halcyon* | Foreach { dotnet pack $_ --output (Join-Path "artifacts\bin" $_.Name) }

after_test:
  - ps: .\scripts\coverage.ps1

artifacts:
  - path: artifacts\bin\Halcyon*\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  on:
   appveyor_repo_tag: true
