version: 1.0.{build}
branches:
  only:
    - master
    - development

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore src/Halcyon.sln

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\Halcyon.sln      # path to Visual Studio solution or project

test_script:
  - ./src/packages/xunit.runner.console.*/tools/xunit.console.exe ./src/Halcyon.Tests/bin/$(configuration)/Halcyon.Tests.dll /appveyor