version: 1.0.{build}
branches:
  only:
    - master
    - development
	
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\Halcyon.sln      # path to Visual Studio solution or project
